Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos9s"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.linked_clone = true
    v.cpus = 1  # Set the number of CPUs
    # v.cpusize = 1024  # Set the CPU execution cap (in percentage)
  end

  # App Server 1
  config.vm.define "Centos-1" do |app|
    app.vm.hostname = "CentOS-1.Fun"
    #app.vm.network :public_network, ip: "192.168.1.120"
    app.vm.network :private_network, ip: "192.168.50.10"
  end

  # App Server 2
  config.vm.define "Centos-2" do |app|
    app.vm.hostname = "CentOS-2.Fun"
    #app.vm.network :public_network, ip: "192.168.1.121"
    app.vm.network :private_network, ip: "192.168.50.11"
  end

  # # DB Server
  # config.vm.define "db" do |db|
  #   db.vm.hostname = "orc.db.test"
  #   db.vm.network :public_network, ip: "192.168.1.122"
  # end


end
